spring:
  profiles:
    active:
    - dev
    
---
server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.xml        # mybatis配置文件所在路径
  type-aliases-package: com.yonyou.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
   profiles: dev
   application:
    name: microservicecloud-dept #向外暴露微服务的名称
   datasource:
    #type: com.alibaba.druid.pool.DruidDataSource    
    type: com.zaxxer.hikari.HikariDataSource        # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/yonyou?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false             # 数据库名称
    username: root
    password: root
    #dbcp2:
     # min-idle: 5                                           # 数据库连接池的最小维持连接数
     # initial-size: 5                                       # 初始化连接数
     # max-total: 5                                          # 最大连接数
     # max-wait-millis: 200                                  # 等待连接获取的最大超时时间
   sleuth:
    #监控开关
     enabled: true
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true     #访问路径可以显示IP地址    
    
info: 
  app.name: yonyou-microservicecloud
  company.name: www.yonyou.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
user:
  name: aaa

---
server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.xml        # mybatis配置文件所在路径
  type-aliases-package: com.yonyou.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
   profiles: test
   application:
    name: microservicecloud-dept #向外暴露微服务的名称
   datasource:
    #type: com.alibaba.druid.pool.DruidDataSource    
    type: com.zaxxer.hikari.HikariDataSource        # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/yonyou2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false             # 数据库名称
    username: root
    password: root
    #dbcp2:
     # min-idle: 5                                           # 数据库连接池的最小维持连接数
     # initial-size: 5                                       # 初始化连接数
     # max-total: 5                                          # 最大连接数
     # max-wait-millis: 200                                  # 等待连接获取的最大超时时间
   sleuth:
    #监控开关
     enabled: true
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true     #访问路径可以显示IP地址    
    
info: 
  app.name: yonyou-microservicecloud
  company.name: www.yonyou.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
user:
  name: bbbaaa
