spring:

  profiles:

    active:

    - dev

    

---
server:
  port: 9527 

spring:
   profiles: dev
   cloud:
    gateway:
      default-filters:
      routes:
      - id: microservicecloud-dept
        uri: lb://MICROSERVICECLOUD-DEPT
        predicates:
          - Path=/microservicecloud-dept/**
        filters:
          - StripPrefix=1

eureka:
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
    hostname: gateway.com
    
    
    
---
server:
  port: 9527 

spring:

   profiles: test
   cloud:
    gateway:
      default-filters:
      routes:
      - id: microservicecloud-dept
        uri: lb://MICROSERVICECLOUD-DEPT
        predicates:
          - Path=/microservicecloud-dept/**
        filters:
          - StripPrefix=1

eureka:
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
    hostname: gateway.com
