server:
  port: 9527


spring:

  profiles:

    active:

    - dev

    

---
   

spring:

   profiles: dev

   application:

      name: microservicecloud-gateway #向外暴露微服务的名称

eureka:
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
    hostname: gateway.com
    
    
    
---
   

spring:

   profiles: test

   application:

      name: microservicecloud-gateway #向外暴露微服务的名称

eureka:
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
    hostname: gateway.com
