spring:
  profiles:
     active:
        - dev
---
spring:
  profiles: dev
  application:
   name: microservicecloud-config-yonyou-dev
   
---
spring:
  profiles: test
  application:
   name: microservicecloud-config-yonyou-test
 

